assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: true
  test: true
instrument: CE01ISSM-MFD35-02-PRESFA000
stream:
  method: recovered_inst
  name: presf_abc_wave_burst_recovered
workflow_config:
  schedule: 0 0 * * *
